<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <ItemGroup>
    <Module Include="src\All.module" />
  </ItemGroup>
  
  <Target Name="BeforeDist">
    <ItemGroup>
      <File Include="$(ImageDir)\**\*">
        <DistPath>WebSites\$(DistLabel)</DistPath>
      </File>
    </ItemGroup>
  </Target>
</Project>
